version: '3.8'

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - backend/.env
    networks:
      bridge_net: 
        ipv4_address: 172.20.0.12

  django: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_web
    volumes:
      - ./backend/OstoriShop:/api 
      - ./backend/OstoriShop/static:/api/static
    ports: 
      - '8000:8000'
    depends_on:
      - pgdb
      - redis
    networks:  
      bridge_net:
        ipv4_address: 172.20.0.10 

  redis:
    image: "redis:7.0.5-alpine"
    container_name: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      bridge_net: 
        ipv4_address: 172.20.0.13

  client-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client-app
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    networks:
      bridge_net: 
        ipv4_address: 172.20.0.11  

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/OstoriShop:/api 
      - ./backend/OstoriShop/static:/static
    depends_on:
      - django
      - client-app  
    networks:
      bridge_net: 
        ipv4_address: 172.20.0.100

    

networks:
  bridge_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 
